# Generated by Django 5.1.4 on 2024-12-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UdomVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('front_id_card', models.ImageField(upload_to='id_cards/front/')),
                ('back_id_card', models.ImageField(upload_to='id_cards/back/')),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
