# Generated by Django 5.1.4 on 2024-12-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('college', models.CharField(default='', max_length=255)),
                ('block', models.CharField(default='', max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='product_images/')),
                ('contact', models.CharField(default='+255', max_length=10)),
            ],
        ),
    ]
